import { MetadataRoute } from "next";

export default function sitemap(): MetadataRoute.Sitemap {
  return [
    {
      url: "https://elcolors.com/sitemaps/visualize/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "yearly",
      priority: 1,
    },
    {
      url: "https://elcolors.com/sitemaps/colors/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "monthly",
      priority: 0.8,
    },
    {
      url: "https://elcolors.com/sitemaps/paletes/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/0/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/1/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/2/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/3/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/4/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/5/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/6/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/7/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/8/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/9/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/10/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/11/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/12/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/13/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/14/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/15/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/16/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/17/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/18/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/19/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/20/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/21/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/22/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/23/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/24/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/25/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/26/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/27/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/28/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/29/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/30/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/31/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/32/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/33/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/34/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/35/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/36/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/37/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/38/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/39/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/40/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/41/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/42/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/43/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/44/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/45/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/46/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/47/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/48/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/49/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/50/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/51/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/52/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/53/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/54/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/55/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/56/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/57/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/58/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/59/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/60/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/61/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/62/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/63/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/64/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/65/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/66/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/67/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/68/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/69/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/70/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/71/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/72/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/73/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/74/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/75/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/76/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/77/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/78/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/79/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/80/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/81/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/82/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/83/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/84/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/85/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/86/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/87/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/88/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/89/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/90/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/91/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/92/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/93/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/94/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/95/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/96/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/97/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/98/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/99/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/100/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },

    {
      url: "https://elcolors.com/sitemaps/100/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/101/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/102/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/103/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/104/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/105/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/106/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/107/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/108/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/109/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/110/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/111/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/112/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/113/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/114/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/115/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/116/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/117/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/118/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/119/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/120/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/121/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/122/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/123/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/124/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/125/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/126/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/127/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/128/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/129/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/130/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/131/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/132/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/133/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/134/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/135/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/136/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/137/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/1138/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/1139/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/140/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/141/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/142/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/143/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/144/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/145/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/146/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/147/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/148/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/149/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/150/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/151/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/152/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/153/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/154/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/155/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/156/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/157/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/158/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/159/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/160/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/161/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/162/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/163/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/164/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/165/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/166/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/167/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/168/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/169/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/170/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/171/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/172/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/173/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/174/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/175/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/176/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/177/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/178/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/179/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/180/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/181/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/182/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/183/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/184/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/185/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/186/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/187/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/188/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/189/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/190/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/191/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/192/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/193/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/194/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/195/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/196/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/197/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/198/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/199/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/200/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/201/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/202/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/203/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/204/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/205/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/206/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/207/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/208/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/209/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/210/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/211/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/212/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/213/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/214/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/215/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/216/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/217/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/218/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/219/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/220/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/221/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/222/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/223/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/224/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/225/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/226/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/227/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/228/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/229/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/230/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/231/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/232/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/233/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/234/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/235/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/236/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/237/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/238/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/239/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/240/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/241/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/242/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/243/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/244/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/245/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/246/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/247/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/248/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/249/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/250/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/251/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/252/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/253/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/254/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/255/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/256/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/257/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/258/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/259/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
    {
      url: "https://elcolors.com/sitemaps/260/sitemap.xml",
      lastModified: new Date(),
      changeFrequency: "weekly",
      priority: 0.5,
    },
  ];
}
